### ISSUE TITLE
Add requests intersphinx

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-data#100]
Failure for astroquery today:

```
intersphinx inventory 'https://requests.kennethreitz.org/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='requests.kennethreitz.org', port=443): Max retries exceeded with url: /en/stable/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f13742c48d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by pllim** [comment]
Do you mean like adding it in https://github.com/astropy/sphinx-astropy/blob/16b9fefce08db880c071059b6973139a4d476c6a/sphinx_astropy/conf/v1.py#L44 ?

**Comment by bsipocz** [comment]
no need to add it to there, but to add the file here, to be able to reuse it the same was as the linked example for astroquery.

low priority issue, but I opened it nevertheless as a reminder.
