### ISSUE TITLE
git on Windows cannot checkout all dirs in testing/astropy

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-data#115]
https://stackoverflow.com/questions/40828718/why-do-i-get-cannot-create-directory-when-checkout-a-git-remote-branch-windows

**Comment by dhomeier** [comment]
Who came up with the idea of creating directories with trailing spaces in their names?

**Comment by pllim** [comment]
In our case, I don't think it is trailing spaces. I think something in the timestamp triggered a similar effect. I was using Git Bash but it was still a native Windows installation.

This is not a problem in WSL2.

**Comment by pllim** [comment]
Directory no longer exists because that testing was refactored.
