### ISSUE TITLE
Incorrect time zone for Mauna Kea site

### ISSUE THREAD

**Issue by shbhuk** [astropy/astropy-data#117]
The current time zone for Keck observatories is incorrect in the `coordinates.json` file. While currently marked as 'US/Aleutian' [here](https://github.com/astropy/astropy-data/blob/4d2c692cf54e37c943e834fafcd4bf9e7a2d9045/coordinates/sites.json#L238), it should be Hawaii Standard Time (US/Hawaii). 

The example code from [here](https://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html#astropy.coordinates.EarthLocation.of_site) can be used to check.

'US/Aleutian' is UTC-9, whereas HST is UTC-10
https://www.timeanddate.com/worldclock/usa/honolulu
http://tdc-www.harvard.edu/iraf/rvsao/bcvcorr/obsdb.html

**Comment by dhomeier** [comment]
Where did you get from that 'US/Aleutian' is at UTC-9?
NIST only recognises a 'Hawaii-Aleutian Time', which _is_ HST at UTC-10 – although the Aleutian Islands have a daylight saving time HDT at UTC-9, but that is not a geographical timezone. UTC-9 is Alaskan (AKST).
https://www.nist.gov/pml/time-and-frequency-division/local-time-faqs#zones

The current designation is somewhat misleading (for all 8 Mauna Kea and Haleakala sites), but it does not look like there is an incorrect TZ offset inferred from it anywhere.

**Comment by shbhuk** [comment]
As follows - 

```
import datetime, pytz
print(datetime.datetime.now(pytz.timezone("US/Aleutian")).utcoffset().total_seconds()/60/60)
```

Prints `-9.0`

**Comment by shbhuk** [comment]
I think the problem might be highlighted in the NIST URL you shared here - 
![image](https://user-images.githubusercontent.com/25436514/133908284-97681748-013a-42cb-b1dd-90f1f08293a0.png)

**Comment by dhomeier** [comment]
Yes; and the `pytz` designation being at least arguably confusing – this is obviously switching automatically to DST for 'US/Aleutian' when applicable:
```python
>>> utc_now = datetime.datetime(2021, 9, 18, 19, 0, 0, tzinfo=pytz.timezone('UTC'))
>>> utc_now.astimezone(pytz.timezone('US/Aleutian'))
datetime.datetime(2021, 9, 18, 10, 0, tzinfo=<DstTzInfo 'US/Aleutian' HDT-1 day, 15:00:00 DST>)
>>> utc_now.astimezone(pytz.timezone('US/Hawaii'))
datetime.datetime(2021, 9, 18, 9, 0, tzinfo=<DstTzInfo 'US/Hawaii' HST-1 day, 14:00:00 STD>)
>>> utc_now.astimezone(pytz.timezone('HST'))
datetime.datetime(2021, 9, 18, 9, 0, tzinfo=<StaticTzInfo 'HST'>)
>>> utc_thx = datetime.datetime(2021, 11, 25, 12, 0, 0, tzinfo=pytz.timezone('UTC'))
>>> utc_thx.astimezone(pytz.timezone('US/Aleutian'))
datetime.datetime(2021, 11, 25, 2, 0, tzinfo=<DstTzInfo 'US/Aleutian' HST-1 day, 14:00:00 STD>)
>>> utc_thx.astimezone(pytz.timezone('US/Hawaii'))
datetime.datetime(2021, 11, 25, 2, 0, tzinfo=<DstTzInfo 'US/Hawaii' HST-1 day, 14:00:00 STD>)
>>> utc_thx.astimezone(pytz.timezone('HST'))
datetime.datetime(2021, 11, 25, 2, 0, tzinfo=<StaticTzInfo 'HST'>)
```
Clearly it would be preferable to use the official TZ abbreviations throughout.

EDIT: from the tz database and e.g. https://home.kpn.nl/vanadovv/time/Multizones.html
'Aleutian' and 'Hawaii' are at least semi-officially denoting the parts observing/not observing DST; so there is a point in using them as they provide both information on the DST rules and the BaseTz/StaticTz. The correct one then of course is 'US/Hawaii'.

**Comment by dhomeier** [comment]
I am volunteering to fix the entries in a PR, preferably after consensus about a consistent format has been reached.
I must say that `pytz`'s treatment of the different formats is somewhat bewildering, e.g.
```python
>>> datetime.datetime.now(pytz.timezone('US/Eastern'))
datetime.datetime(2021, 10, 9, 14, 49, 39, 25761, tzinfo=<DstTzInfo 'US/Eastern' EDT-1 day, 20:00:00 DST>)
>>> datetime.datetime.now(pytz.timezone('EST'))
datetime.datetime(2021, 10, 9, 13, 50, 1, 567091, tzinfo=<StaticTzInfo 'EST'>)
>>> datetime.datetime.now(pytz.timezone('US/Mountain'))
datetime.datetime(2021, 10, 9, 11, 50, 13, 203518, tzinfo=<DstTzInfo 'US/Mountain' MDT-1 day, 18:00:00 DST>)
>>> datetime.datetime.now(pytz.timezone('MST'))
datetime.datetime(2021, 10, 9, 10, 50, 21, 434496, tzinfo=<StaticTzInfo 'MST'>)
```
whereas for the European timezones
```python
>>> datetime.datetime.now(pytz.timezone('Europe/Paris'))
datetime.datetime(2021, 10, 9, 20, 50, 33, 594535, tzinfo=<DstTzInfo 'Europe/Paris' CEST+2:00:00 DST>)
>>> datetime.datetime.now(pytz.timezone('CET'))
datetime.datetime(2021, 10, 9, 20, 50, 46, 475846, tzinfo=<DstTzInfo 'CET' CEST+2:00:00 DST>)
```
and `CST`, `PST` are not accepted at all...
That means replacing `CET` with `Europe/Capital` would probably have no practical effect (unless we had an entry for [`Europe/Zurich` in the summer of 1980](https://en.wikipedia.org/wiki/Europe/Zurich)...), but still be more easily recognisable IMO.
