### ISSUE TITLE
Remove testing/astropy ?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-data#132]
https://github.com/astropy/astropy-data/tree/gh-pages/testing/astropy has been replaced by https://github.com/astropy/astropy-figure-tests , right, @astrofrog or @Cadair ?

**Comment by Cadair** [comment]
Yes as far as I am aware we don't need it any more. We should just check that we don't have an LTS branch using the old files or something?

**Comment by pllim** [comment]
Can always wait till when we cut astropy 6.0

**Comment by pllim** [comment]
Actually, @astrofrog backported https://github.com/astropy/astropy/pull/13596 , so I think we can delete.
