### ISSUE TITLE
Storing 10-100Gb of data on the data server for Halotools

### ISSUE THREAD

**Issue by aphearin** [astropy/astropy-data#3]
I currently have 2.5Gb of data stored as hdf5 files stored in several in the following web location:
http://www.astro.yale.edu/aphearin/Data_files/halo_catalogs

The files are organized into subdirectories of this location, and I would like the entire directory and its contents on the data server. These files contain reduced dark matter halo catalogs that have been pre-processed by Halotools, so that users can quickly get up and running with N-body simulation analysis. 

This is following up on a discussion with @eteq , who told me to also ping @astrofrog . 

For the present needs of Halotools, and for the next several months, I only need <~10Gb of space. However, before the first official package release (towards the end of 2015), I will need more like a few hundred Gb of space. The reason is that I would also like to provide pre-processed binaries of merger trees, not just single-snapshot halo catalogs. 

I realize that astropy-data is not really configured for this kind of volume, and that this may take some time, so I'm raising the issue significantly in advance of my package release, as suggested by @eteq .

**Comment by astrofrog** [comment]
If the STScI server allows this, maybe we could upload it directly there and bypass this repository?

**Comment by aphearin** [comment]
Certainly fine by me. Anything better than my personal website, which is necessarily temporary, would be preferable.

**Comment by aphearin** [comment]
@astrofrog - Was I supposed to check myself with someone at STScI about this? I don't mind, of course, but I don't know who the right contact point is.

**Comment by astrofrog** [comment]
@aphearin - no, sorry for the delay! Maybe @perrygreenfield could comment on this?

**Comment by perrygreenfield** [comment]
I'll have to see what space we have available for this sort of thing. Give me a day or two. You would think that given raw disk space costing less than $25/TB these days that this would be a minor issue, but they use more expensive storage systems for servers, and the overheads on those, management of the disk space, etc. don't make it quite so trivial.

**Comment by aphearin** [comment]
No problem. I'm just progressing a little faster than I thought. And the specs have changed a bit as well. In the short term, it's still the case that all I need is ~10Gb to store a few snapshots that have been pre-processed. But in about a month(ish), it looks like I'll have also have finished producing pre-processed binaries of merger trees, and my new estimate for the total size needs is now more like 1Tb per simulation. Starting out with just a single simulation is perfectly fine.

**Comment by aphearin** [comment]
Thanks for looking into it, @perrygreenfield . I'm familiar with the roadblocks of storing large amounts of simulation data, so I didn't expect it to be trivial to find a home for the data.

**Comment by aphearin** [comment]
Let me know if it would be helpful/necessary to make a science case for the space.

**Comment by astrofrog** [comment]
@aphearin - just one question, to make sure I understand - is this dataset meant to be _the_ dataset to use with halotools, or just an example dataset?

**Comment by aphearin** [comment]
It will be _the_ dataset. Though it will need to be occasionally updated by me (or whoever is in charge of Halotools down the line).

**Comment by aphearin** [comment]
To be clear, the package supports the use of _any_ simulated dataset provided by the user, so that users can work with their own simulations, including their own proprietary ones. But there will only ever be a small collection of simulation reductions that Halotools will provide via astropy.data, and these will be (by far) the most commonly used ones. Make sense?

**Comment by adrn** [comment]
Haven't been following this thread but what about using [Git LFS](https://git-lfs.github.com/)?
