### ISSUE TITLE
Inconsistencies in longitude sign in coordinates' sites.json file.

### ISSUE THREAD

**Issue by gully** [astropy/astropy-data#30]
There seems to be an inconsistency in the sign of longitudes in the `sites.json` file.  For example, Siding Spring Observatory should be at about 149 East longitude, the NASA IRTF should be at about 155 West longitude, Lick Observatory should be at 121 West, and La Palma should be at about 17 deg West longitude.  But what we see in the sites.json file is inconsistent (output truncated to highlight problem):

```json
"sso": {
    "name": "Siding Spring Observatory",
    "longitude": 149.06119444444445}

"irtf": {
    "name": "NASA Infrared Telescope Facility",
    "longitude": 155.4719987888889}  ##Should be 204.5280012111111

"lick": {
    "name": "Lick Observatory",
    "longitude": 238.36333333333332}

"lapalma": {
    "name": "Roque de los Muchachos, La Palma",
    "longitude": 342.12}
```

When employed in `coordinates.EarthLocation()` we see:

```python
for site in ['sso', 'irtf', 'lick', 'lapalma']:
    print(coordinates.EarthLocation.of_site(site).lon)

149d03m40.3s
155d28m19.1956s
-121d38m12s
-17d52m48s
```

But I think it *should* be:
```python
149d03m40.3s
-155d28m19.1956s ## <- IRTF
-121d38m12s
-17d52m48s
```

This inconsistency arose from different standards for representing longitude.  The `irtf` data came in commit 808c025 which has other entries using negative longitudes, but those seem OK.

**Comment by astrofrog** [comment]
cc @eteq

**Comment by pllim** [comment]
Also c/c @StuartLittlefair @adrn

**Comment by eteq** [comment]
Thanks @gully - you're 100% correct here - sorry it's taken so long to notice/correct, but I did so in  96aeaa3 . 

The key point is that it is *intended* that it be possible to use the either the 255 or the *minus* 155 option, but the +155 is wrong just as you inferred.  But it should now be fixed.  Thanks!
