### ISSUE TITLE
BUG: Fix sites.json so Astropy remote data tests pass again

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-data#36]
I think the fix is to replace special characters introduced in astropy/astropy-data#34. However, if I am wrong, please do whatever is correct and then close this issue when tests are passing again.

p.s. Maybe we need to find a way to test this stuff over at astropy side before merging.

**Comment by bsipocz** [comment]
I guess we can set up some travis testing here, too.

**Comment by eteq** [comment]
Note that I've got a fix to make this not an issue in astropy in astropy/astropy#7082.

*however* : even with that fix, the non-ascii characters mean that older versions of astropy will now fail on the site registry.  So we might want to back-out the specific offending change.  I've implemented that in #38 , which we can merge if we think astropy/astropy#7082 is not sufficient (i.e. we want to restore function in older astropys). Opinions?

cc @astrofrog @taldcroft (I think this also may cause some of the `astropy.time` tests to act up?) @bmorris3 @adrn @pllim

**Comment by pllim** [comment]
IMHO unless you want to backport astropy/astropy#7082 to all supported versions, better to merge #38 and then re-introduce special characters when all the supported `astropy` versions can read them. However, I could be overruled.

**Comment by saimn** [comment]
I think the best is to merge quickly #38 to fix builds (and also released versions ?). The non-ascii name can be reintroduced later, once all released versions support this.

**Comment by eteq** [comment]
OK, I merged #38 so I think we can call this done.  I agree with @saimn's proposal so will make a separate issue to track that.
