### ISSUE TITLE
Set up CI for this repo

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-data#37]
We need to set up some basic CI testing to make sure changes in this repo doesn't introduce a regression in the astropy core testing, see #36 

This can be assigned to me, and will try to come back to it in a few days time.

**Comment by pllim** [comment]
I don't have permission to assign you to this but I like the idea. Thanks!

**Comment by eteq** [comment]
I agree and as a minimum it could just do the instructions here: https://github.com/astropy/astropy-data/blob/gh-pages/coordinates/README.md to validate the file (although I don't think that would have acught #36)

**Comment by aarchiba** [comment]
To manage (for example) #40 , we could perhaps arrange to run the test suites of various astropy versions against the repository?

**Comment by pllim** [comment]
`astropy` already tests its release branches at https://travis-ci.org/astropy/astropy/branches . But running some here with *released* tags is a good idea.

**Comment by pllim** [comment]
Should revisit this to prevent future #102

**Comment by pllim** [comment]
I added a CI to check `sites.json`. If y'all think there are more things we can test, feel free to open up PRs. The infrastructure is there.
