### ISSUE TITLE
Big data warning from GitHub

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-data#66]
Might want to consider making that tutorial use a smaller file and get rid of `synchrotron_i_lobe_0700_150MHz.fits`. cc @eblur and @adrn 

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File tutorials/synthetic-images/synchrotron_i_lobe_0700_150MHz.fits is 64.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

**Comment by bsipocz** [comment]
Ouch. But given it's in history already I suppose we can live with it rather than add in a slightly smaller one.

**Comment by pllim** [comment]
I wanna suggest that we squash all commits in `master` to a single commit from time to time, but that is probably too controversial. :sweat_smile: 

Feel free to close if we can safely ignore this warning.

**Comment by bsipocz** [comment]
Squashing to a singe one is very drastic.
But if we're OK of force pushing to master, I'm willing to do the occasional cleanup of big files leaving everything but the offending commits in place.
