### ISSUE TITLE
Remove old matplotlib comparison images?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-data#68]
Do we need all the old matplotlib comparison images under https://github.com/astropy/astropy-data/tree/gh-pages/testing/astropy ?

With astropy/astropy#8787 , only `matplotlib>=2.1` is supported now for `master` branch.

**Comment by astrofrog** [comment]
@pllim - the older ones are needed in case people with old versions of astropy run tests (and we still run CircleCI on LTS)

**Comment by bsipocz** [comment]
I also wonder whether it makes any difference to remove them, they are already in the git history.

**Comment by astrofrog** [comment]
We get the files via the 'published' gh-pages branch which only reflects the latest commit. Remember that these are synced to a separate web server which doesn't have the history of the files, just the latest version.

**Comment by bsipocz** [comment]
oh, fair enough. Another argument could be that even if the size of the git history doesn't change, removing them declutters the files visible on master.

**Comment by astrofrog** [comment]
@bsipocz - I agree that over time we can remove them to tidy up, but while we still support LTS we should keep them.

**Comment by pllim** [comment]
Okay, feel free to close this if you want. Thanks for the clarification!
