### ISSUE TITLE
Add pytest intersphinx

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-data#71]
without a way to automate the updates for the intersphinx mappings this may be suboptimal, but having links pointing to an old version is still better than the current way of failing docs  builds on astropy core.

This is somewhat related to #69

**Comment by pllim** [comment]
Perhaps related: astropy/astropy#9033 and pytest-dev/pytest#5641

**Comment by bsipocz** [comment]
yes, this would add a workaround for the cases in the issues above.

**Comment by pllim** [comment]
So, I guess this means we cannot delete our mirrors here, as brought for for discussions over at #69?

**Comment by bsipocz** [comment]
yes, I think I'm changing my hasted opinion in that issue. We better have something even if outdated than failing docs build CI runs. Ideally we have updated intersphinx, but then I'm not sure it's worth the effort of coming up with an update machinery.
