### ISSUE TITLE
Astropy Data Mirror

### ISSUE THREAD

**Issue by jbcurtin** [astropy/astropy-data#91]
hello,

  STScI built a mirror for `http://www.astropy.org/astropy-data/`. It can be found here,
https://astropy-data.s3.us-east-1.amazonaws.com/data/index.html

  To update the mirror, install the following URL as a GET request in Github Hooks
https://la6fmo7tpj.execute-api.us-east-1.amazonaws.com/main/astropy_hook

Where may we share a copy of the source codes?

**Comment by stscicrawford** [comment]
@eteq any chance a repository can be created in astropy for the source code to support this?

**Comment by pllim** [comment]
Both people here have left STScI, so I don't think this is happening anymore.
